# Change these first
owner: thomas-senechal # Your GitHub organization or username, where this repository lives
repo: website-status # The name of this repository

sites:
  - name: Massa
    url: https://massa.net
  - name: Gitlab
    url: https://gitlab.com
  - name: Optispace
    url: http://optispace.fr
  - name: Optispace APP
    url: http://app.optispace.fr
  - name: Optispace Engine
    url: http://engine.optispace.fr

status-website:
  baseUrl: /website-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Massa status
  introTitle: "Massa status website."
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
